NorthWestOrderSystem/NorthWestOrderSystem/Controllers/AssayTypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NorthWestOrderSystem.DAL;
using NorthWestOrderSystem.Models;

namespace NorthWestOrderSystem.Controllers
{
    public class AssayTypesController : Controller
    {
        private IntexContext db = new IntexContext();

        // GET: AssayTypes
        public ActionResult Index()
        {
            return View(db.AssayTypes.ToList());
        }

        // GET: AssayTypes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AssayType assayType = db.AssayTypes.Find(id);
            if (assayType == null)
            {
                return HttpNotFound();
            }
            return View(assayType);
        }

        // GET: AssayTypes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AssayTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AssayID,AssayTitle,FullDescription,Summary,BasePrice,Procedures")] AssayType assayType)
        {
            if (ModelState.IsValid)
            {
                db.AssayTypes.Add(assayType);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(assayType);
        }

        // GET: AssayTypes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AssayType assayType = db.AssayTypes.Find(id);
            if (assayType == null)
            {
                return HttpNotFound();
            }
            return View(assayType);
        }

        // POST: AssayTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AssayID,AssayTitle,FullDescription,Summary,BasePrice,Procedures")] AssayType assayType)
        {
            if (ModelState.IsValid)
            {
                db.Entry(assayType).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(assayType);
        }

        // GET: AssayTypes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AssayType assayType = db.AssayTypes.Find(id);
            if (assayType == null)
            {
                return HttpNotFound();
            }
            return View(assayType);
        }

        // POST: AssayTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AssayType assayType = db.AssayTypes.Find(id);
            db.AssayTypes.Remove(assayType);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult AssayTypesList()
        {
            return View("AssayTypesList");
        }

        public ActionResult Catalog()
        {
            return View("Catalog");
        }

        public ActionResult BiochemicalPharmocology()
        {
            AssayType assayType = db.AssayTypes.Find(1);
            return View(assayType);
        }
    }
}

NorthWestOrderSystem/NorthWestOrderSystem/Views/AssayTypes/AssayTypesList.cshtml
@{
    ViewBag.Title = "Select Assay Type";
}

<h2>Please Select an Assay Type</h2>

@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <hr />
        <div class="table">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <select class="form-control">
                            <option disabled selected>Search Assay Types</option>
                            <option>Biochemical Pharmacology (BP)</option>
                            <option>DiscoveryScreen® (DS)</option>
                            <option>ImmunoScreen® (IS)</option>
                            <option>ProfilingScreen® (PF)</option>
                            <option>PharmaScreen® (PS)</option>
                            <option>CustomScreen™ (CS)</option>
                            <option>Other</option>
                        </select>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <select class="form-control">
                            <option disabled selected>Search Active Orders</option>
                            <option>#1345334</option>
                            <option>#1423423</option>
                            <option>#1433884</option>
                            <option>#1419488</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>
        <br />
        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <a>@Html.ActionLink("Continue", "NewTest", "Employees", null, null)</a>
            </div>
        </div>
    </div>
}
<br />
<br />
<br />

NorthWestOrderSystem/NorthWestOrderSystem/Views/AssayTypes/BiochemicalPharmocology.cshtml
@model NorthWestOrderSystem.Models.AssayType

@{
    ViewBag.Title = "Biochemical Pharmocology";
}

<h2>Biochemical Pharmocology</h2>

<div>
    <hr />
    <div class="table">
        <div class="row">
            <div class="col-md-6">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.AssayTitle)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.AssayTitle)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.FullDescription)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.FullDescription)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Summary)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Summary)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.BasePrice)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.BasePrice)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Procedures)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Procedures)
                    </dd>

                </dl>
            </div>
            <div class="col-md-6">
                <img src="~/Content/Images/biochemicalPharmacology.jpg" />
            </div>
        </div>

    </div>
    
    
</div>
<p>
    @Html.ActionLink("Home", "Index", "Home", null, null)
</p>

NorthWestOrderSystem/NorthWestOrderSystem/Views/AssayTypes/Catalog.cshtml
@model IEnumerable<NorthWestOrderSystem.Models.AssayType>

@{
    ViewBag.Title = "Assay Catalog";
}

<div style="text-align:center">
    <h2 style="font-size:30px">Assay Catalog</h2>
</div>
<hr />
<div class="row" style="text-align:center">
    <div class="col-md-4">
        <h3>Biochemical Pharmacology (BP)</h3>
        <br />
        <a href='@Url.Action("BiochemicalPharmocology", "AssayTypes")'><img class="photo" src="~/Content/Images/biochemicalPharmacology.jpg" style="width:90%" /></a>
    </div>
    <div class="col-md-4">
        <h3> DiscoveryScreen® (DS)</h3>
        <br />
        <a href='@Url.Action("Index", "Home")'><img class="photo" src="~/Content/Images/discoveryScreen.jpg" style="width:90%" /></a>
    </div>
    <div class="col-md-4">
        <h3>ImmunoScreen® (IS)</h3>
        <br />
        <a href='@Url.Action("Index", "Home")'><img class="photo" src="~/Content/Images/immunoScreen.jpg" style="width:90%" /></a>
    </div>
</div>
<br />
<div class="row" style="text-align:center">
    <div class="col-md-4">
        <h3>ProfilingScreen® (PF)</h3>
        <br />
        <a href='@Url.Action("Index", "Home")'><img class="photo" src="~/Content/Images/ProfilingScreen.jpg" style="width:90%" /></a>
    </div>
    <div class="col-md-4">
        <h3>PharmaScreen® (PS)</h3>
        <br />
        <a href='@Url.Action("Index", "Home")'><img class="photo" src="~/Content/Images/pharmaScreen.jpg" style="width:90%" /></a>
    </div>
    <div class="col-md-4">
        <h3>CustomScreen™ (CS)</h3>
        <br />
        <a href='@Url.Action("Index", "Home")'><img class="photo" src="~/Content/Images/customScreen.jpg" style="width:90%" /></a>
    </div>
</div>
<br />
<div class="row" style="text-align:center">
    <div class="col-md-4">
        <h3>Other</h3>
        <br />
        <a href='@Url.Action("Index", "Home")'><img class="photo" src="~/Content/Images/labStation-Other.jpg" style="width:90%" /></a>
    </div>
</div>
<hr />
<div>
    <a href='@Url.Action("Index", "Home")' class='btn btn-default btn-primary' style="margin-left:100px;">Home</a>
</div>

NorthWestOrderSystem/NorthWestOrderSystem/Views/AssayTypes/Create.cshtml
@model NorthWestOrderSystem.Models.AssayType

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AssayType</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.AssayTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AssayTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AssayTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FullDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Summary, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Summary, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Summary, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BasePrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BasePrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BasePrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Procedures, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Procedures, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Procedures, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

NorthWestOrderSystem/NorthWestOrderSystem/Views/AssayTypes/Delete.cshtml
@model NorthWestOrderSystem.Models.AssayType

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AssayType</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AssayTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AssayTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FullDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Summary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Summary)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BasePrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BasePrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Procedures)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Procedures)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

NorthWestOrderSystem/NorthWestOrderSystem/Views/AssayTypes/Details.cshtml
@model NorthWestOrderSystem.Models.AssayType

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>AssayType</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AssayTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AssayTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FullDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Summary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Summary)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BasePrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BasePrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Procedures)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Procedures)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.AssayID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

NorthWestOrderSystem/NorthWestOrderSystem/Views/AssayTypes/Edit.cshtml
@model NorthWestOrderSystem.Models.AssayType

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AssayType</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.AssayID)

        <div class="form-group">
            @Html.LabelFor(model => model.AssayTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AssayTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AssayTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FullDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Summary, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Summary, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Summary, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BasePrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BasePrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BasePrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Procedures, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Procedures, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Procedures, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

NorthWestOrderSystem/NorthWestOrderSystem/Views/AssayTypes/Index.cshtml
@model IEnumerable<NorthWestOrderSystem.Models.AssayType>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.AssayTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FullDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Summary)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BasePrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Procedures)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.AssayTitle)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FullDescription)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Summary)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BasePrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Procedures)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.AssayID }) |
            @Html.ActionLink("Details", "Details", new { id=item.AssayID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.AssayID })
        </td>
    </tr>
}

</table>